title: Yingjia Liew
author: Yingjia Liew
logo: assets/img/TabbyPic.jpg
description: This is my cat, Tabby. 
url: "https://mliew.github.io"
url: "https://blog.csdn.net/qq_39560620?type=blog"
auto: true
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag
- jemoji

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: Configure the Guide
  internal: true
  url: configure-the-guide
- text: GitHub Setup
  internal: true
  url: github
- text: Create a Glossary
  glossary: true
- text: Edit this Repo
  internal: false
  url: https://github.com/DCgov/guides-template
