title: Yingjia Liew
title: Yingjia Liew 
author: Yingjia Liew
logo: assets/img/GithubProfileImage_1.jpg
description: 
url: "https://mliew.github.io"
auto: true
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag
- jemoji

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Navigation
# List links that should appear in the site sidebar here
# navigation:
# - text: Edit this Repo
 #  internal: false
 #  url: https://github.com/DCgov/guides-template
